configuration: Release

version: 1.0.{build}

image: Visual Studio 2017

build:
    parallel: true
    publish_nuget: true
    verbosity: minimal

before_build:
  - dotnet restore
  
branches:
    only:
      - master

deploy:
  provider: NuGet
  api_key:
    secure: JhXouXJJXYiQ9aSRg5EHLD+0JVi539qjs7BM2BjGXncFbcR6zo7FQ3X8vBe8m/Sd
  skip_symbols: false
  artifact: /.*\.nupkg/
  
    

  
  


